# Generated by Django 4.2 on 2023-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('media_type', models.CharField(max_length=255)),
                ('media_url', models.URLField()),
            ],
        ),
    ]
