# Generated by Django 4.2 on 2023-04-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.TextField(),
        ),
    ]
